@extends('layouts.app')

@php
    $userName = explode(' ', Auth::user()->name)[0];
    $periodString = $periodDate->translatedFormat('F Y');
    $currentDate = now()->translatedFormat('M d, Y');
@endphp

@section('content')
<div class="container-fluid px-4 py-3">

    <!-- Header Greeting Section -->
    <div class="d-flex justify-content-between align-items-center mb-5">
        <div>
            <h1 class="h2 font-weight-bold text-gray-900 mb-1">Welcome back, {{ $userName }}!</h1>
            <p class="text-muted small mb-0 font-weight-medium">Inter, 24px • {{ $currentDate }}</p>
        </div>
        <a href="{{ route('transactions.create') }}" class="btn btn-primary px-4 py-2 font-weight-bold" style="border-radius: 10px; background-color: #3b82f6; border: none;">
            Add Transaction
        </a>
    </div>

    <!-- Main Dashboard Row (Cards) -->
    <div class="row">
        <!-- Total Net Worth Card -->
        <div class="col-xl-4 col-lg-5 mb-4">
            <div class="card h-100 border-0 shadow-sm" style="border-radius: 16px;">
                <div class="card-body p-4 d-flex flex-column">
                    <div class="mb-auto">
                        <div class="text-muted small font-weight-bold mb-2">Total Net Worth</div>
                        <div class="h2 font-weight-bold text-gray-900 mb-1">
                            {{ $currencySymbol }} {{ number_format($totalCash, 0, ',', '.') }}
                        </div>
                        <div class="small font-weight-bold {{ $netWorthTrend >= 0 ? 'text-success' : 'text-danger' }}">
                            {{ $netWorthTrend >= 0 ? '+' : '' }}{{ number_format($netWorthTrend, 1) }}% this month
                        </div>
                    </div>
                    <!-- Sparkline Chart Placeholder (Matching the airy wave in the image) -->
                    <div class="mt-4" style="height: 60px; width: 100%;">
                        <canvas id="netWorthSparkline"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Cash Flow Card (Inflow/Outflow side by side) -->
        <div class="col-xl-2 col-lg-3 mb-4">
            <div class="card h-100 border-0 shadow-sm" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="text-muted small font-weight-bold mb-3">Cash Flow</div>
                    
                    <div class="mb-4">
                        <div class="text-muted small mb-1">Inflow</div>
                        <div class="h4 font-weight-bold text-gray-900 mb-0">
                            {{ $currencySymbol }} {{ number_format($totalIncome, 0, ',', '.') }}
                        </div>
                    </div>

                    <div>
                        <div class="text-muted small mb-1">Outflow</div>
                        <div class="h4 font-weight-bold text-gray-900 mb-0">
                            {{ $currencySymbol }} {{ number_format($totalExpense, 0, ',', '.') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Monthly Expenses Donut Chart -->
        <div class="col-xl-6 col-lg-4 mb-4">
            <div class="card h-100 border-0 shadow-sm" style="border-radius: 16px;">
                <div class="card-header bg-white border-0 d-flex justify-content-between align-items-center py-3 px-4">
                    <div class="text-muted small font-weight-bold">{{ $periodDate->translatedFormat('F') }} Expenses</div>
                    <div class="dropdown no-arrow">
                        <button class="btn btn-link btn-sm dropdown-toggle text-muted font-weight-medium border" style="border-radius: 8px; text-decoration: none;">
                            Category <i class="fas fa-chevron-down small ml-1"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body px-4 py-2">
                    <div class="row align-items-center">
                        <div class="col-md-6 text-center position-relative">
                            <canvas id="expensesDonutChart" style="max-height: 180px;"></canvas>
                            <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); pointer-events: none;">
                                <div class="text-muted small mb-0">Total {{ $periodDate->translatedFormat('F') }}</div>
                                <div class="font-weight-bold text-gray-900">{{ $currencySymbol }} {{ number_format($totalExpense, 0, ',', '.') }}</div>
                            </div>
                        </div>
                        <div class="col-md-6 pt-3 pt-md-0">
                            <div id="expensesLegend" class="small">
                                <!-- Legend generated by JS -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Transactions Table Section -->
    <div class="row mt-2">
        <div class="col-12">
            <div class="card border-0 shadow-sm" style="border-radius: 16px;">
                <div class="card-header bg-white border-0 py-4 px-4 d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="font-weight-bold text-gray-900 mb-1">Recent Transactions</h5>
                        <p class="text-muted small mb-0">Soft fonts for Inter, #101828</p>
                    </div>
                    <a href="{{ route('transactions.create') }}" class="btn btn-primary btn-sm px-3 py-2 font-weight-bold" style="border-radius: 8px;">
                        Add Transaction
                    </a>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0" style="font-size: 0.9rem;">
                            <thead class="bg-light border-0">
                                <tr class="text-muted">
                                    <th class="border-0 px-4 py-3 font-weight-medium">Date</th>
                                    <th class="border-0 py-3 font-weight-medium">Description</th>
                                    <th class="border-0 py-3 font-weight-medium">Category</th>
                                    <th class="border-0 py-3 font-weight-medium">Account</th>
                                    <th class="border-0 py-3 font-weight-medium text-right pr-4">Amount</th>
                                    <th class="border-0 py-3 font-weight-medium text-center">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($recentTransactions as $transaction)
                                    <tr style="border-bottom: 1px solid #f8fafc;">
                                        <td class="px-4 py-3 text-muted">{{ $transaction->transaction_date->translatedFormat('M d') }}</td>
                                        <td class="py-3 font-weight-medium text-gray-900">{{ $transaction->description }}</td>
                                        <td class="py-3">
                                            <span class="px-2 py-1 rounded" style="background-color: rgba(59, 130, 246, 0.05); color: #475569; font-size: 0.8rem;">
                                                {{ $transaction->category->name ?? 'Uncategorized' }}
                                            </span>
                                        </td>
                                        <td class="py-3 text-muted">{{ $transaction->account->name ?? '-' }}</td>
                                        <td class="py-3 text-right pr-4 font-weight-bold {{ $transaction->type == 'expense' ? 'text-danger' : 'text-success' }}">
                                            {{ $transaction->type == 'expense' ? '-' : '+' }}
                                            {{ $transaction->account->setting->currency_symbol ?? $currencySymbol }} 
                                            {{ number_format($transaction->amount, 0, ',', '.') }}
                                        </td>
                                        <td class="py-3 text-center">
                                            <span class="small font-weight-bold text-muted">Cleared</span>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center py-5 text-muted">No recent transactions found.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

@section('scripts')
<script src="{{ asset('vendor/chart.js/Chart.min.js') }}"></script>
<script>
    // Net Worth Sparkline
    const ctxSpark = document.getElementById('netWorthSparkline').getContext('2d');
    new Chart(ctxSpark, {
        type: 'line',
        data: {
            labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
            datasets: [{
                data: [100, 110, 105, 120, 115, 130, 125, 140, 135, 150],
                borderColor: '#3b82f6',
                borderWidth: 2,
                fill: true,
                backgroundColor: 'rgba(59, 130, 246, 0.05)',
                pointRadius: 0,
                tension: 0.4
            }]
        },
        options: {
            maintainAspectRatio: false,
            legend: { display: false },
            scales: {
                xAxes: [{ display: false }],
                yAxes: [{ display: false }]
            }
        }
    });

    // Expenses Donut Chart
    const ctxDonut = document.getElementById('expensesDonutChart').getContext('2d');
    const expenseData = @json($expenseCategories);
    
    const chartData = {
        labels: expenseData.map(d => d.name),
        datasets: [{
            data: expenseData.map(d => d.total),
            backgroundColor: [
                '#3b82f6', '#c084fc', '#60a5fa', '#f87171', '#fb923c', '#fbbf24', '#34d399'
            ],
            borderWidth: 0,
            hoverOffset: 4
        }]
    };

    const expensesChart = new Chart(ctxDonut, {
        type: 'doughnut',
        data: chartData,
        options: {
            maintainAspectRatio: false,
            cutoutPercentage: 75,
            legend: { display: false },
            tooltips: {
                callbacks: {
                    tags: function(tooltipItem, data) {
                        const tags = data.labels[tooltipItem.index];
                        const value = data.datasets[0].data[tooltipItem.index];
                        return tags + ': {{ $currencySymbol }} ' + new Intl.NumberFormat('id-ID').format(value);
                    }
                }
            }
        }
    });

    // Custom Legend
    const legendContainer = document.getElementById('expensesLegend');
    const total = expenseData.reduce((acc, curr) => acc + parseFloat(curr.total), 0);
    
    expenseData.forEach((item, index) => {
        const percent = total > 0 ? ((item.total / total) * 100).toFixed(0) : 0;
        const color = chartData.datasets[0].backgroundColor[index % chartData.datasets[0].backgroundColor.length];
        
        const legendItem = document.createElement('div');
        legendItem.className = 'd-flex align-items-center justify-content-between mb-2';
        legendItem.innerHTML = `
            <div class="d-flex align-items-center">
                <div style="width: 8px; height: 8px; border-radius: 50%; background-color: ${color}; margin-right: 10px;"></div>
                <span class="text-muted font-weight-medium">${item.name}</span>
            </div>
            <span class="text-gray-900 font-weight-bold">${percent}%</span>
        `;
        legendContainer.appendChild(legendItem);
    });
</script>
@endsection
